### ISSUE TITLE
Not enough value to unpack

### ISSUE THREAD

**Issue by enzyme69** [mathigatti/midi2voice#5]
I kept getting an error when running it on my machine:

```python

192-168-1-10:midi2voice-master jimmygunawan$ python3 midi2voice.py ./inputs/shallow.txt ./inputs/shallow.mid 
Traceback (most recent call last):
  File "midi2voice.py", line 6, in <module>
    from midi2xml import midi2xml
  File "/Users/jimmygunawan/midi2voice-master/midi2xml.py", line 3, in <module>
    from lyrics_tokenizer import tokenize
  File "/Users/jimmygunawan/midi2voice-master/lyrics_tokenizer.py", line 2, in <module>
    from music21 import converter, instrument, note, chord
  File "/usr/local/lib/python3.7/site-packages/music21/__init__.py", line 169, in <module>
    from music21 import base  # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/music21/base.py", line 66, in <module>
    from music21 import environment
  File "/usr/local/lib/python3.7/site-packages/music21/environment.py", line 816, in <module>
    _environStorage['instance'] = _EnvironmentCore()
  File "/usr/local/lib/python3.7/site-packages/music21/environment.py", line 175, in __init__
    self._loadDefaults(forcePlatform=forcePlatform)
  File "/usr/local/lib/python3.7/site-packages/music21/environment.py", line 405, in _loadDefaults
    versionTuple = common.macOSVersion()
  File "/usr/local/lib/python3.7/site-packages/music21/common/misc.py", line 117, in macOSVersion
    major, minor, maintenance = tuple(int(v) for v in platform.mac_ver()[0].split('.'))
ValueError: not enough values to unpack (expected 3, got 2)
192-168-1-10:midi2voice-master jimmygunawan$ 
```

**Comment by enzyme69** [comment]
My feeling is that here on MacOS, I cannot run the mscore or musescore from commandline, not sure how to add it to PATH.

**Comment by mathigatti** [comment]
Hi, the error in midi2code seems to arise at midi2xml.py line number 3 `from music21 import converter, instrument, note, chord
`

So it looks like music21 is broken for MacOS, maybe if you try installing an older version?

Something like this maybe: pip install music21==5.7.2
